### ISSUE TITLE
[Bug]: curl_multi_exec() request failure on 0.94.0

### ISSUE THREAD

**Issue by Julian-Louis** [DataDog/dd-trace-php#2390]
### Bug report

Hello, I installed this package yesterday (23 November 2023).
Every thing seems to be working fine except that some https://github.com/async-aws/dynamo-db-session requests appears as errors:
<img width="1631" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/86676740/cf40093b-c0b7-465d-ad84-2e4efa47b366">

I took a look at the changelog of the installed release `0.94.0`:
<img width="631" alt="Screenshot 2023-11-24 at 15 53 01" src="https://github.com/DataDog/dd-trace-php/assets/86676740/c8e5ca78-d708-48ae-b6bb-864a6783e146"> 

I saw that a new feature (https://github.com/DataDog/dd-trace-php/pull/2347) related to my error was implemented, so I tried with version `0.93.2`and I don't have any https://github.com/async-aws/dynamo-db-session curls spans anymore. (It's normal, as the curl_multi_exec() tracer was not implemented)

## More context

<img width="1629" alt="Screenshot 2023-11-24 at 16 14 14" src="https://github.com/DataDog/dd-trace-php/assets/86676740/b30a4e35-f243-4cd6-920e-d28883cb64e2">
<img width="678" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/86676740/d538ae68-b515-4935-af42-a75b17e62596">
<img width="698" alt="image" src="https://github.com/DataDog/dd-trace-php/assets/86676740/6485ee00-ab33-42bd-8263-49d4de3b7700">

The HTTP request seems to be successful as `http.status_code` is 200
But as the `curl.connect_time` is 0, an exception is thrown ([see commit](https://github.com/DataDog/dd-trace-php/commit/b1b6851e12615bc9cad400daa6d28a8259512a55#diff-f8cd63a50c940d53741be8e05bef840e3a5d1682bf5ee3ed239673c34521caeeR131))
I'm not sure to understand why `curl.connect_time` is 0, but I also don't understand why the span contain an error because the http request return a 200 status code 

I hope I have been understood,
Feel free to ask me questions,
Thank you in advance

### PHP version

8.1.25

### Tracer or profiler version

0.94.0

### Installed extensions

```
[PHP Modules]
bcmath
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
gd
hash
iconv
imagick
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
SimpleXML
soap
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddtrace
```

### Upgrading from

0.93.2

**Comment by bwoebi** [comment]
I have a suspicion that curl reuses connections and thus curl.connect_time is a bad indicator (as it'll be 0 then). We'll have to verify, thanks for the report!

**Comment by PROFeNoM** [comment]
Hey @Julian-Louis!

Could you please try out this [artifact](https://output.circle-artifacts.com/output/job/756b1ad6-18df-4b21-8952-21e610e5a31b/artifacts/0/datadog-setup.php) (from this [CI Job](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/13693/workflows/82e1e5ed-6e9d-4b5f-b048-32370de61cfe/jobs/3282135/artifacts)) and tell us if it helps with the behavior you're observing? It uses the http_code instead of relying on connect_time to detect curl request failures 😃 

PS: To use the artifact, you can replace the list of the [installer](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/13693/workflows/82e1e5ed-6e9d-4b5f-b048-32370de61cfe/jobs/3282135/artifacts) by the one from the CI Job, which includes the changes :+1:

**Comment by Julian-Louis** [comment]
Hello, I've just tried the artifact and the problem seems to have been solved.
Do you need anything else?

**Comment by PROFeNoM** [comment]
Thanks for your prompt feedback @Julian-Louis :smiley:

Since it appears to have solved the issue, we shouldn't need anything else from you. On my side, I'll do the PR, including this commit, and we'll possibly see for a hotfix :+1:

Thanks!

**Comment by Julian-Louis** [comment]
Thank you @PROFeNoM and @bwoebi !

**Comment by sfong22** [comment]
I believe the solution implemented by @PROFeNoM and @bwoebi solved some cases but I am still seeing error traces with a non-zero connect time and dynamodb http code is 200 but the trace is displaying as errored. Would it be most appropriate to leave details here or to open a separate issue? What would be most helpful to your team in that report to determine if this is an ongoing issue or expected behavior?

**Comment by Julian-Louis** [comment]
Hello @sfong22, it seems that the fix is not yet release, so we should be waiting for the next release of this project (0.95.0).
You can look in the milestone (https://github.com/DataDog/dd-trace-php/milestone/161?closed=1).

**Comment by PROFeNoM** [comment]
Hi @sfong22 and @Julian-Louis,

I apologize for the delay. I am happy to let you know that version 0.95.0, including the required fix, has been released. You can find more information about this version on the [release notes](https://github.com/DataDog/dd-trace-php/releases/tag/0.95.0). 

Thank you for your patience! 😃

**Comment by sfong22** [comment]
@PROFeNoM Thank you for the update!

I had compared the PR closure to the latest release but didn't actually check the release notes.

Thank you guys for your active monitoring of this repository and all your quick replies.
